name = "Cyber Hugo"
license = "MIT"
licenselink = "https://github.com/maxzhirnov/cyber-hugo/blob/main/LICENSE"
description = "A cyberpunk-inspired Hugo theme with neon aesthetics, glowing elements, and retro-futuristic styling."
homepage = "https://github.com/maxzhirnov/cyber-hugo"
tags = ["cyberpunk", "dark", "neon", "tailwind", "responsive", "blog", "portfolio", "search"]
features = [
  "Responsive design",
  "Dark mode",
  "Client-side search",
  "Custom shortcodes",
  "Table of contents",
  "Cyberpunk styling",
  "Tailwind CSS"
]
min_version = "0.88.0"

[author]
  name = "Maksim Zhirnov"
  homepage = "https://github.com/maxzhirnov/"
